# Generated by Django 5.1.1 on 2024-09-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0004_alter_control_threats'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='attributes',
            field=models.ManyToManyField(related_name='controls', to='risks.attribute'),
        ),
    ]
