from django.urls import path
from risks import views as risks_views

urlpatterns = [
    path('', risks_views.ProductList.as_view(), name='product_list'),
    path('product/', risks_views.ProductList.as_view(), name='product_list'),
    path('product/<int:pk>/', risks_views.ProductDetail.as_view(), name='product_detail'),
    path('product/add/', risks_views.ProductCreate.as_view(), name='product_add'),
    path('product/<int:pk>/edit/', risks_views.ProductUpdate.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', risks_views.ProductDelete.as_view(), name='product_delete'),
    path('component/', risks_views.ComponentList.as_view(), name='component_list'),
    path('component/<int:pk>/', risks_views.ComponentDetail.as_view(), name='component_detail'),
    path('component/add/', risks_views.ComponentCreate.as_view(), name='component_add'),
    path('component/<int:pk>/edit/', risks_views.ComponentUpdate.as_view(), name='component_update'),
    path('component/<int:pk>/delete/', risks_views.ComponentDelete.as_view(), name='component_delete'),
    path('attribute/', risks_views.AttributeList.as_view(), name='attribute_list'),
    path('attribute/<int:pk>/', risks_views.AttributeDetail.as_view(), name='attribute_detail'),
    path('attribute/add/', risks_views.AttributeCreate.as_view(), name='attribute_add'),
    path('attribute/<int:pk>/edit/', risks_views.AttributeUpdate.as_view(), name='attribute_update'),
    path('attribute/<int:pk>/delete/', risks_views.AttributeDelete.as_view(), name='attribute_delete'),
    path('threat/', risks_views.ThreatList.as_view(), name='threat_list'),
    path('threat/<int:pk>/', risks_views.ThreatDetail.as_view(), name='threat_detail'),
    path('threat/add/', risks_views.ThreatCreate.as_view(), name='threat_add'),
    path('threat/<int:pk>/edit/', risks_views.ThreatUpdate.as_view(), name='threat_update'),
    path('threat/<int:pk>/delete/', risks_views.ThreatDelete.as_view(), name='threat_delete'),
    path('control/', risks_views.ControlList.as_view(), name='control_list'),
    path('control/<int:pk>/', risks_views.ControlDetail.as_view(), name='control_detail'),
    path('control/add/', risks_views.ControlCreate.as_view(), name='control_add'),
    path('control/<int:pk>/edit/', risks_views.ControlUpdate.as_view(), name='control_update'),
    path('control/<int:pk>/delete/', risks_views.ControlDelete.as_view(), name='control_delete'),
    path('implemented_control/', risks_views.ImplementedControlList.as_view(), name='implemented_control_list'),
    path('implemented_control/<int:pk>/', risks_views.ImplementedControlDetail.as_view(), name='implemented_control_detail'),
    path('implemented_control/add/', risks_views.ImplementedControlCreate.as_view(), name='implemented_control_add'),
    path('implemented_control/<int:pk>/edit/', risks_views.ImplementedControlUpdate.as_view(), name='implemented_control_update'),
    path('implemented_control/<int:pk>/delete/', risks_views.ImplementedControlDelete.as_view(), name='implemented_control_delete'),
    path('category/', risks_views.CategoryList.as_view(), name='category_list'),
    path('category/<int:pk>/', risks_views.CategoryDetail.as_view(), name='category_detail'),
    path('category/add/', risks_views.CategoryCreate.as_view(), name='category_add'),
    path('category/<int:pk>/edit/', risks_views.CategoryUpdate.as_view(), name='category_update'),
    path('category/<int:pk>/delete/', risks_views.CategoryDelete.as_view(), name='category_delete'),
]
